### ISSUE TITLE
Double Voting

### ISSUE THREAD

**Issue by BreslinRy** [BreslinRy/SE310-420-Project#1]
You can vote for more than one candidate

**Comment by Strick9ers** [comment]
Bug Classification: defect
Bug Location: GUI.py
Bug Priority: 3
How to reproduce:
1. User Selects both candidates
2. User submits vote
Expected Result:
Clears users previous input when another candidate is selected.
Actual Result:
Saves users vote as one for each candidate.

**Comment by Strick9ers** [comment]
Fixed in the new version using radio buttons
